# coding: utf-8

"""
    ChannelEngine Merchant API

    ChannelEngine API for merchants  # noqa: E501

    OpenAPI spec version: 2.17.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import channelengine_client
from channelengine_client.models.single_merchant_acknowledge_return_request import SingleMerchantAcknowledgeReturnRequest  # noqa: E501
from channelengine_client.rest import ApiException


class TestSingleMerchantAcknowledgeReturnRequest(unittest.TestCase):
    """SingleMerchantAcknowledgeReturnRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSingleMerchantAcknowledgeReturnRequest(self):
        """Test SingleMerchantAcknowledgeReturnRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = channelengine_client.models.single_merchant_acknowledge_return_request.SingleMerchantAcknowledgeReturnRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
