# coding: utf-8

"""
    ChannelEngine Merchant API

    ChannelEngine API for merchants  # noqa: E501

    OpenAPI spec version: 2.17.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import channelengine_client
from channelengine_client.models.merchant_fulfillment_stock_stock_locations_response import MerchantFulfillmentStockStockLocationsResponse  # noqa: E501
from channelengine_client.rest import ApiException


class TestMerchantFulfillmentStockStockLocationsResponse(unittest.TestCase):
    """MerchantFulfillmentStockStockLocationsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMerchantFulfillmentStockStockLocationsResponse(self):
        """Test MerchantFulfillmentStockStockLocationsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = channelengine_client.models.merchant_fulfillment_stock_stock_locations_response.MerchantFulfillmentStockStockLocationsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
