# coding: utf-8

"""
    ChannelEngine Merchant API

    ChannelEngine API for merchants  # noqa: E501

    OpenAPI spec version: 2.17.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import channelengine_client
from channelengine_client.models.single_of_i_refund import SingleOfIRefund  # noqa: E501
from channelengine_client.rest import ApiException


class TestSingleOfIRefund(unittest.TestCase):
    """SingleOfIRefund unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSingleOfIRefund(self):
        """Test SingleOfIRefund"""
        # FIXME: construct object with mandatory attributes with example values
        # model = channelengine_client.models.single_of_i_refund.SingleOfIRefund()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
