# coding: utf-8

"""
    ChannelEngine Merchant API

    ChannelEngine API for merchants  # noqa: E501

    OpenAPI spec version: 2.17.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import channelengine_client
from channelengine_client.api.webhooks_api import WebhooksApi  # noqa: E501
from channelengine_client.rest import ApiException


class TestWebhooksApi(unittest.TestCase):
    """WebhooksApi unit test stubs"""

    def setUp(self):
        self.api = WebhooksApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_webhooks_create(self):
        """Test case for webhooks_create

        Creates a webhook  # noqa: E501
        """
        pass

    def test_webhooks_delete(self):
        """Test case for webhooks_delete

        Deletes a webhook  # noqa: E501
        """
        pass

    def test_webhooks_get_all(self):
        """Test case for webhooks_get_all

        Gets webhooks  # noqa: E501
        """
        pass

    def test_webhooks_update(self):
        """Test case for webhooks_update

        Updates a webhook  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
