# coding: utf-8

"""
    ChannelEngine Merchant API

    ChannelEngine API for merchants  # noqa: E501

    OpenAPI spec version: 2.17.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import channelengine_client
from channelengine_client.models.modules_tax_registration_type import ModulesTaxRegistrationType  # noqa: E501
from channelengine_client.rest import ApiException


class TestModulesTaxRegistrationType(unittest.TestCase):
    """ModulesTaxRegistrationType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testModulesTaxRegistrationType(self):
        """Test ModulesTaxRegistrationType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = channelengine_client.models.modules_tax_registration_type.ModulesTaxRegistrationType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
