# coding: utf-8

"""
    ChannelEngine Merchant API

    ChannelEngine API for merchants  # noqa: E501

    OpenAPI spec version: 2.17.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import channelengine_client
from channelengine_client.models.merchant_product_with_buy_box_price import MerchantProductWithBuyBoxPrice  # noqa: E501
from channelengine_client.rest import ApiException


class TestMerchantProductWithBuyBoxPrice(unittest.TestCase):
    """MerchantProductWithBuyBoxPrice unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMerchantProductWithBuyBoxPrice(self):
        """Test MerchantProductWithBuyBoxPrice"""
        # FIXME: construct object with mandatory attributes with example values
        # model = channelengine_client.models.merchant_product_with_buy_box_price.MerchantProductWithBuyBoxPrice()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
