# coding: utf-8

"""
    ChannelEngine Merchant API

    ChannelEngine API for merchants  # noqa: E501

    OpenAPI spec version: 2.17.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import channelengine_client
from channelengine_client.api.settlements_api import SettlementsApi  # noqa: E501
from channelengine_client.rest import ApiException


class TestSettlementsApi(unittest.TestCase):
    """SettlementsApi unit test stubs"""

    def setUp(self):
        self.api = SettlementsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_settlement_get_by_filter(self):
        """Test case for settlement_get_by_filter

        Gets settlements  # noqa: E501
        """
        pass

    def test_settlement_upload_settlement(self):
        """Test case for settlement_upload_settlement

        Uploads a settlement file to ChannelEngine.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
