# coding: utf-8

"""
    ChannelEngine Merchant API

    ChannelEngine API for merchants  # noqa: E501

    OpenAPI spec version: 2.17.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import channelengine_client
from channelengine_client.api.targets_api import TargetsApi  # noqa: E501
from channelengine_client.rest import ApiException


class TestTargetsApi(unittest.TestCase):
    """TargetsApi unit test stubs"""

    def setUp(self):
        self.api = TargetsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_targets_create_targets(self):
        """Test case for targets_create_targets

        Creates multiple targets  # noqa: E501
        """
        pass

    def test_targets_delete_targets(self):
        """Test case for targets_delete_targets

        Deletes multiple targets  # noqa: E501
        """
        pass

    def test_targets_edit_targets(self):
        """Test case for targets_edit_targets

        Edits multiple targets  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
