# coding: utf-8

"""
    ChannelEngine Merchant API

    ChannelEngine API for merchants  # noqa: E501

    OpenAPI spec version: 2.17.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import channelengine_client
from channelengine_client.models.single_merchant_create_purchase_order_invoice_request import SingleMerchantCreatePurchaseOrderInvoiceRequest  # noqa: E501
from channelengine_client.rest import ApiException


class TestSingleMerchantCreatePurchaseOrderInvoiceRequest(unittest.TestCase):
    """SingleMerchantCreatePurchaseOrderInvoiceRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSingleMerchantCreatePurchaseOrderInvoiceRequest(self):
        """Test SingleMerchantCreatePurchaseOrderInvoiceRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = channelengine_client.models.single_merchant_create_purchase_order_invoice_request.SingleMerchantCreatePurchaseOrderInvoiceRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
