# coding: utf-8

"""
    ChannelEngine Merchant API

    ChannelEngine API for merchants  # noqa: E501

    OpenAPI spec version: 2.17.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import channelengine_client
from channelengine_client.api.product_attributes_api import ProductAttributesApi  # noqa: E501
from channelengine_client.rest import ApiException


class TestProductAttributesApi(unittest.TestCase):
    """ProductAttributesApi unit test stubs"""

    def setUp(self):
        self.api = ProductAttributesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_product_attribute_group_add_product_extra_data(self):
        """Test case for product_attribute_group_add_product_extra_data

        Adds custom attributes to a group  # noqa: E501
        """
        pass

    def test_product_attribute_group_create(self):
        """Test case for product_attribute_group_create

        Creates a custom attribute group  # noqa: E501
        """
        pass

    def test_product_attribute_group_delete(self):
        """Test case for product_attribute_group_delete

        Deletes a custom attribute group  # noqa: E501
        """
        pass

    def test_product_attribute_group_get_by_filter(self):
        """Test case for product_attribute_group_get_by_filter

        Gets custom attribute groups  # noqa: E501
        """
        pass

    def test_product_attribute_group_get_with_channels_by_filter(self):
        """Test case for product_attribute_group_get_with_channels_by_filter

        Gets custom attribute groups and linked marketplaces  # noqa: E501
        """
        pass

    def test_product_attribute_group_remove_product_extra_data(self):
        """Test case for product_attribute_group_remove_product_extra_data

        Deletes custom attributes from a group  # noqa: E501
        """
        pass

    def test_product_attribute_group_rename_product_attribute_group(self):
        """Test case for product_attribute_group_rename_product_attribute_group

        Renames custom attribute groups  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
