# coding: utf-8

"""
    ChannelEngine Merchant API

    ChannelEngine API for merchants  # noqa: E501

    OpenAPI spec version: 2.17.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import channelengine_client
from channelengine_client.api.purchase_orders_api import PurchaseOrdersApi  # noqa: E501
from channelengine_client.rest import ApiException


class TestPurchaseOrdersApi(unittest.TestCase):
    """PurchaseOrdersApi unit test stubs"""

    def setUp(self):
        self.api = PurchaseOrdersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_acknowledge(self):
        """Test case for acknowledge

        Acknowledges lines of a purchase order  # noqa: E501
        """
        pass

    def test_create(self):
        """Test case for create

        Create a purchase order shipment.  # noqa: E501
        """
        pass

    def test_get_by_filter(self):
        """Test case for get_by_filter

        Gets purchase order shipments by filter  # noqa: E501
        """
        pass

    def test_get_by_filter_0(self):
        """Test case for get_by_filter_0

        Gets purchase orders by filter  # noqa: E501
        """
        pass

    def test_purchase_orders_create_invoice(self):
        """Test case for purchase_orders_create_invoice

        Creates a purchase order invoice  # noqa: E501
        """
        pass

    def test_purchase_orders_create_invoices(self):
        """Test case for purchase_orders_create_invoices

        Creates a purchase order invoices in a bulk  # noqa: E501
        """
        pass

    def test_update(self):
        """Test case for update

        Update a purchase order shipment.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
