# coding: utf-8

"""
    ChannelEngine Merchant API

    ChannelEngine API for merchants  # noqa: E501

    OpenAPI spec version: 2.17.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import channelengine_client
from channelengine_client.models.product_extra_data_request import ProductExtraDataRequest  # noqa: E501
from channelengine_client.rest import ApiException


class TestProductExtraDataRequest(unittest.TestCase):
    """ProductExtraDataRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProductExtraDataRequest(self):
        """Test ProductExtraDataRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = channelengine_client.models.product_extra_data_request.ProductExtraDataRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
