# coding: utf-8

"""
    ChannelEngine Merchant API

    ChannelEngine API for merchants  # noqa: E501

    OpenAPI spec version: 2.17.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class MerchantAcknowledgePurchaseOrder(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'identifier': 'str',
        'merchant_order_no': 'str',
        'lines': 'list[MerchantAcknowledgePurchaseOrderLine]'
    }

    attribute_map = {
        'identifier': 'Identifier',
        'merchant_order_no': 'MerchantOrderNo',
        'lines': 'Lines'
    }

    def __init__(self, identifier=None, merchant_order_no=None, lines=None):  # noqa: E501
        """MerchantAcknowledgePurchaseOrder - a model defined in Swagger"""  # noqa: E501
        self._identifier = None
        self._merchant_order_no = None
        self._lines = None
        self.discriminator = None
        if identifier is not None:
            self.identifier = identifier
        if merchant_order_no is not None:
            self.merchant_order_no = merchant_order_no
        if lines is not None:
            self.lines = lines

    @property
    def identifier(self):
        """Gets the identifier of this MerchantAcknowledgePurchaseOrder.  # noqa: E501


        :return: The identifier of this MerchantAcknowledgePurchaseOrder.  # noqa: E501
        :rtype: str
        """
        return self._identifier

    @identifier.setter
    def identifier(self, identifier):
        """Sets the identifier of this MerchantAcknowledgePurchaseOrder.


        :param identifier: The identifier of this MerchantAcknowledgePurchaseOrder.  # noqa: E501
        :type: str
        """

        self._identifier = identifier

    @property
    def merchant_order_no(self):
        """Gets the merchant_order_no of this MerchantAcknowledgePurchaseOrder.  # noqa: E501


        :return: The merchant_order_no of this MerchantAcknowledgePurchaseOrder.  # noqa: E501
        :rtype: str
        """
        return self._merchant_order_no

    @merchant_order_no.setter
    def merchant_order_no(self, merchant_order_no):
        """Sets the merchant_order_no of this MerchantAcknowledgePurchaseOrder.


        :param merchant_order_no: The merchant_order_no of this MerchantAcknowledgePurchaseOrder.  # noqa: E501
        :type: str
        """

        self._merchant_order_no = merchant_order_no

    @property
    def lines(self):
        """Gets the lines of this MerchantAcknowledgePurchaseOrder.  # noqa: E501


        :return: The lines of this MerchantAcknowledgePurchaseOrder.  # noqa: E501
        :rtype: list[MerchantAcknowledgePurchaseOrderLine]
        """
        return self._lines

    @lines.setter
    def lines(self, lines):
        """Sets the lines of this MerchantAcknowledgePurchaseOrder.


        :param lines: The lines of this MerchantAcknowledgePurchaseOrder.  # noqa: E501
        :type: list[MerchantAcknowledgePurchaseOrderLine]
        """

        self._lines = lines

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MerchantAcknowledgePurchaseOrder, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MerchantAcknowledgePurchaseOrder):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
