# coding: utf-8

"""
    ChannelEngine Merchant API

    ChannelEngine API for merchants  # noqa: E501

    OpenAPI spec version: 2.17.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class MerchantPurchaseOrderInvoiceLine(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'channel_purchase_order_no': 'str',
        'merchant_purchase_order_no': 'str',
        'channel_product_no': 'str',
        'merchant_product_no': 'str',
        'quantity': 'int',
        'net_cost_currency_code': 'str',
        'net_cost_amount': 'float',
        'hsn_code': 'str',
        'cn_reference_invoice_number': 'str',
        'cn_debit_note_number': 'str',
        'cn_returns_reference_number': 'str',
        'cn_rma_id': 'str',
        'cn_goods_return_date': 'datetime',
        'cn_coop_reference_number': 'str',
        'cn_consignors_reference_number': 'str',
        'allowance_details': 'list[PurchaseOrderInvoiceAllowanceDetails]',
        'tax_details': 'list[PurchaseOrderInvoiceTaxDetails]',
        'charge_details': 'list[PurchaseOrderInvoiceChargeDetails]'
    }

    attribute_map = {
        'channel_purchase_order_no': 'ChannelPurchaseOrderNo',
        'merchant_purchase_order_no': 'MerchantPurchaseOrderNo',
        'channel_product_no': 'ChannelProductNo',
        'merchant_product_no': 'MerchantProductNo',
        'quantity': 'Quantity',
        'net_cost_currency_code': 'NetCostCurrencyCode',
        'net_cost_amount': 'NetCostAmount',
        'hsn_code': 'HsnCode',
        'cn_reference_invoice_number': 'CnReferenceInvoiceNumber',
        'cn_debit_note_number': 'CnDebitNoteNumber',
        'cn_returns_reference_number': 'CnReturnsReferenceNumber',
        'cn_rma_id': 'CnRmaId',
        'cn_goods_return_date': 'CnGoodsReturnDate',
        'cn_coop_reference_number': 'CnCoopReferenceNumber',
        'cn_consignors_reference_number': 'CnConsignorsReferenceNumber',
        'allowance_details': 'AllowanceDetails',
        'tax_details': 'TaxDetails',
        'charge_details': 'ChargeDetails'
    }

    def __init__(self, channel_purchase_order_no=None, merchant_purchase_order_no=None, channel_product_no=None, merchant_product_no=None, quantity=None, net_cost_currency_code=None, net_cost_amount=None, hsn_code=None, cn_reference_invoice_number=None, cn_debit_note_number=None, cn_returns_reference_number=None, cn_rma_id=None, cn_goods_return_date=None, cn_coop_reference_number=None, cn_consignors_reference_number=None, allowance_details=None, tax_details=None, charge_details=None):  # noqa: E501
        """MerchantPurchaseOrderInvoiceLine - a model defined in Swagger"""  # noqa: E501
        self._channel_purchase_order_no = None
        self._merchant_purchase_order_no = None
        self._channel_product_no = None
        self._merchant_product_no = None
        self._quantity = None
        self._net_cost_currency_code = None
        self._net_cost_amount = None
        self._hsn_code = None
        self._cn_reference_invoice_number = None
        self._cn_debit_note_number = None
        self._cn_returns_reference_number = None
        self._cn_rma_id = None
        self._cn_goods_return_date = None
        self._cn_coop_reference_number = None
        self._cn_consignors_reference_number = None
        self._allowance_details = None
        self._tax_details = None
        self._charge_details = None
        self.discriminator = None
        if channel_purchase_order_no is not None:
            self.channel_purchase_order_no = channel_purchase_order_no
        if merchant_purchase_order_no is not None:
            self.merchant_purchase_order_no = merchant_purchase_order_no
        if channel_product_no is not None:
            self.channel_product_no = channel_product_no
        if merchant_product_no is not None:
            self.merchant_product_no = merchant_product_no
        if quantity is not None:
            self.quantity = quantity
        if net_cost_currency_code is not None:
            self.net_cost_currency_code = net_cost_currency_code
        if net_cost_amount is not None:
            self.net_cost_amount = net_cost_amount
        if hsn_code is not None:
            self.hsn_code = hsn_code
        if cn_reference_invoice_number is not None:
            self.cn_reference_invoice_number = cn_reference_invoice_number
        if cn_debit_note_number is not None:
            self.cn_debit_note_number = cn_debit_note_number
        if cn_returns_reference_number is not None:
            self.cn_returns_reference_number = cn_returns_reference_number
        if cn_rma_id is not None:
            self.cn_rma_id = cn_rma_id
        if cn_goods_return_date is not None:
            self.cn_goods_return_date = cn_goods_return_date
        if cn_coop_reference_number is not None:
            self.cn_coop_reference_number = cn_coop_reference_number
        if cn_consignors_reference_number is not None:
            self.cn_consignors_reference_number = cn_consignors_reference_number
        if allowance_details is not None:
            self.allowance_details = allowance_details
        if tax_details is not None:
            self.tax_details = tax_details
        if charge_details is not None:
            self.charge_details = charge_details

    @property
    def channel_purchase_order_no(self):
        """Gets the channel_purchase_order_no of this MerchantPurchaseOrderInvoiceLine.  # noqa: E501


        :return: The channel_purchase_order_no of this MerchantPurchaseOrderInvoiceLine.  # noqa: E501
        :rtype: str
        """
        return self._channel_purchase_order_no

    @channel_purchase_order_no.setter
    def channel_purchase_order_no(self, channel_purchase_order_no):
        """Sets the channel_purchase_order_no of this MerchantPurchaseOrderInvoiceLine.


        :param channel_purchase_order_no: The channel_purchase_order_no of this MerchantPurchaseOrderInvoiceLine.  # noqa: E501
        :type: str
        """

        self._channel_purchase_order_no = channel_purchase_order_no

    @property
    def merchant_purchase_order_no(self):
        """Gets the merchant_purchase_order_no of this MerchantPurchaseOrderInvoiceLine.  # noqa: E501


        :return: The merchant_purchase_order_no of this MerchantPurchaseOrderInvoiceLine.  # noqa: E501
        :rtype: str
        """
        return self._merchant_purchase_order_no

    @merchant_purchase_order_no.setter
    def merchant_purchase_order_no(self, merchant_purchase_order_no):
        """Sets the merchant_purchase_order_no of this MerchantPurchaseOrderInvoiceLine.


        :param merchant_purchase_order_no: The merchant_purchase_order_no of this MerchantPurchaseOrderInvoiceLine.  # noqa: E501
        :type: str
        """

        self._merchant_purchase_order_no = merchant_purchase_order_no

    @property
    def channel_product_no(self):
        """Gets the channel_product_no of this MerchantPurchaseOrderInvoiceLine.  # noqa: E501


        :return: The channel_product_no of this MerchantPurchaseOrderInvoiceLine.  # noqa: E501
        :rtype: str
        """
        return self._channel_product_no

    @channel_product_no.setter
    def channel_product_no(self, channel_product_no):
        """Sets the channel_product_no of this MerchantPurchaseOrderInvoiceLine.


        :param channel_product_no: The channel_product_no of this MerchantPurchaseOrderInvoiceLine.  # noqa: E501
        :type: str
        """

        self._channel_product_no = channel_product_no

    @property
    def merchant_product_no(self):
        """Gets the merchant_product_no of this MerchantPurchaseOrderInvoiceLine.  # noqa: E501


        :return: The merchant_product_no of this MerchantPurchaseOrderInvoiceLine.  # noqa: E501
        :rtype: str
        """
        return self._merchant_product_no

    @merchant_product_no.setter
    def merchant_product_no(self, merchant_product_no):
        """Sets the merchant_product_no of this MerchantPurchaseOrderInvoiceLine.


        :param merchant_product_no: The merchant_product_no of this MerchantPurchaseOrderInvoiceLine.  # noqa: E501
        :type: str
        """

        self._merchant_product_no = merchant_product_no

    @property
    def quantity(self):
        """Gets the quantity of this MerchantPurchaseOrderInvoiceLine.  # noqa: E501


        :return: The quantity of this MerchantPurchaseOrderInvoiceLine.  # noqa: E501
        :rtype: int
        """
        return self._quantity

    @quantity.setter
    def quantity(self, quantity):
        """Sets the quantity of this MerchantPurchaseOrderInvoiceLine.


        :param quantity: The quantity of this MerchantPurchaseOrderInvoiceLine.  # noqa: E501
        :type: int
        """

        self._quantity = quantity

    @property
    def net_cost_currency_code(self):
        """Gets the net_cost_currency_code of this MerchantPurchaseOrderInvoiceLine.  # noqa: E501


        :return: The net_cost_currency_code of this MerchantPurchaseOrderInvoiceLine.  # noqa: E501
        :rtype: str
        """
        return self._net_cost_currency_code

    @net_cost_currency_code.setter
    def net_cost_currency_code(self, net_cost_currency_code):
        """Sets the net_cost_currency_code of this MerchantPurchaseOrderInvoiceLine.


        :param net_cost_currency_code: The net_cost_currency_code of this MerchantPurchaseOrderInvoiceLine.  # noqa: E501
        :type: str
        """

        self._net_cost_currency_code = net_cost_currency_code

    @property
    def net_cost_amount(self):
        """Gets the net_cost_amount of this MerchantPurchaseOrderInvoiceLine.  # noqa: E501


        :return: The net_cost_amount of this MerchantPurchaseOrderInvoiceLine.  # noqa: E501
        :rtype: float
        """
        return self._net_cost_amount

    @net_cost_amount.setter
    def net_cost_amount(self, net_cost_amount):
        """Sets the net_cost_amount of this MerchantPurchaseOrderInvoiceLine.


        :param net_cost_amount: The net_cost_amount of this MerchantPurchaseOrderInvoiceLine.  # noqa: E501
        :type: float
        """

        self._net_cost_amount = net_cost_amount

    @property
    def hsn_code(self):
        """Gets the hsn_code of this MerchantPurchaseOrderInvoiceLine.  # noqa: E501


        :return: The hsn_code of this MerchantPurchaseOrderInvoiceLine.  # noqa: E501
        :rtype: str
        """
        return self._hsn_code

    @hsn_code.setter
    def hsn_code(self, hsn_code):
        """Sets the hsn_code of this MerchantPurchaseOrderInvoiceLine.


        :param hsn_code: The hsn_code of this MerchantPurchaseOrderInvoiceLine.  # noqa: E501
        :type: str
        """

        self._hsn_code = hsn_code

    @property
    def cn_reference_invoice_number(self):
        """Gets the cn_reference_invoice_number of this MerchantPurchaseOrderInvoiceLine.  # noqa: E501


        :return: The cn_reference_invoice_number of this MerchantPurchaseOrderInvoiceLine.  # noqa: E501
        :rtype: str
        """
        return self._cn_reference_invoice_number

    @cn_reference_invoice_number.setter
    def cn_reference_invoice_number(self, cn_reference_invoice_number):
        """Sets the cn_reference_invoice_number of this MerchantPurchaseOrderInvoiceLine.


        :param cn_reference_invoice_number: The cn_reference_invoice_number of this MerchantPurchaseOrderInvoiceLine.  # noqa: E501
        :type: str
        """

        self._cn_reference_invoice_number = cn_reference_invoice_number

    @property
    def cn_debit_note_number(self):
        """Gets the cn_debit_note_number of this MerchantPurchaseOrderInvoiceLine.  # noqa: E501


        :return: The cn_debit_note_number of this MerchantPurchaseOrderInvoiceLine.  # noqa: E501
        :rtype: str
        """
        return self._cn_debit_note_number

    @cn_debit_note_number.setter
    def cn_debit_note_number(self, cn_debit_note_number):
        """Sets the cn_debit_note_number of this MerchantPurchaseOrderInvoiceLine.


        :param cn_debit_note_number: The cn_debit_note_number of this MerchantPurchaseOrderInvoiceLine.  # noqa: E501
        :type: str
        """

        self._cn_debit_note_number = cn_debit_note_number

    @property
    def cn_returns_reference_number(self):
        """Gets the cn_returns_reference_number of this MerchantPurchaseOrderInvoiceLine.  # noqa: E501


        :return: The cn_returns_reference_number of this MerchantPurchaseOrderInvoiceLine.  # noqa: E501
        :rtype: str
        """
        return self._cn_returns_reference_number

    @cn_returns_reference_number.setter
    def cn_returns_reference_number(self, cn_returns_reference_number):
        """Sets the cn_returns_reference_number of this MerchantPurchaseOrderInvoiceLine.


        :param cn_returns_reference_number: The cn_returns_reference_number of this MerchantPurchaseOrderInvoiceLine.  # noqa: E501
        :type: str
        """

        self._cn_returns_reference_number = cn_returns_reference_number

    @property
    def cn_rma_id(self):
        """Gets the cn_rma_id of this MerchantPurchaseOrderInvoiceLine.  # noqa: E501


        :return: The cn_rma_id of this MerchantPurchaseOrderInvoiceLine.  # noqa: E501
        :rtype: str
        """
        return self._cn_rma_id

    @cn_rma_id.setter
    def cn_rma_id(self, cn_rma_id):
        """Sets the cn_rma_id of this MerchantPurchaseOrderInvoiceLine.


        :param cn_rma_id: The cn_rma_id of this MerchantPurchaseOrderInvoiceLine.  # noqa: E501
        :type: str
        """

        self._cn_rma_id = cn_rma_id

    @property
    def cn_goods_return_date(self):
        """Gets the cn_goods_return_date of this MerchantPurchaseOrderInvoiceLine.  # noqa: E501


        :return: The cn_goods_return_date of this MerchantPurchaseOrderInvoiceLine.  # noqa: E501
        :rtype: datetime
        """
        return self._cn_goods_return_date

    @cn_goods_return_date.setter
    def cn_goods_return_date(self, cn_goods_return_date):
        """Sets the cn_goods_return_date of this MerchantPurchaseOrderInvoiceLine.


        :param cn_goods_return_date: The cn_goods_return_date of this MerchantPurchaseOrderInvoiceLine.  # noqa: E501
        :type: datetime
        """

        self._cn_goods_return_date = cn_goods_return_date

    @property
    def cn_coop_reference_number(self):
        """Gets the cn_coop_reference_number of this MerchantPurchaseOrderInvoiceLine.  # noqa: E501


        :return: The cn_coop_reference_number of this MerchantPurchaseOrderInvoiceLine.  # noqa: E501
        :rtype: str
        """
        return self._cn_coop_reference_number

    @cn_coop_reference_number.setter
    def cn_coop_reference_number(self, cn_coop_reference_number):
        """Sets the cn_coop_reference_number of this MerchantPurchaseOrderInvoiceLine.


        :param cn_coop_reference_number: The cn_coop_reference_number of this MerchantPurchaseOrderInvoiceLine.  # noqa: E501
        :type: str
        """

        self._cn_coop_reference_number = cn_coop_reference_number

    @property
    def cn_consignors_reference_number(self):
        """Gets the cn_consignors_reference_number of this MerchantPurchaseOrderInvoiceLine.  # noqa: E501


        :return: The cn_consignors_reference_number of this MerchantPurchaseOrderInvoiceLine.  # noqa: E501
        :rtype: str
        """
        return self._cn_consignors_reference_number

    @cn_consignors_reference_number.setter
    def cn_consignors_reference_number(self, cn_consignors_reference_number):
        """Sets the cn_consignors_reference_number of this MerchantPurchaseOrderInvoiceLine.


        :param cn_consignors_reference_number: The cn_consignors_reference_number of this MerchantPurchaseOrderInvoiceLine.  # noqa: E501
        :type: str
        """

        self._cn_consignors_reference_number = cn_consignors_reference_number

    @property
    def allowance_details(self):
        """Gets the allowance_details of this MerchantPurchaseOrderInvoiceLine.  # noqa: E501


        :return: The allowance_details of this MerchantPurchaseOrderInvoiceLine.  # noqa: E501
        :rtype: list[PurchaseOrderInvoiceAllowanceDetails]
        """
        return self._allowance_details

    @allowance_details.setter
    def allowance_details(self, allowance_details):
        """Sets the allowance_details of this MerchantPurchaseOrderInvoiceLine.


        :param allowance_details: The allowance_details of this MerchantPurchaseOrderInvoiceLine.  # noqa: E501
        :type: list[PurchaseOrderInvoiceAllowanceDetails]
        """

        self._allowance_details = allowance_details

    @property
    def tax_details(self):
        """Gets the tax_details of this MerchantPurchaseOrderInvoiceLine.  # noqa: E501


        :return: The tax_details of this MerchantPurchaseOrderInvoiceLine.  # noqa: E501
        :rtype: list[PurchaseOrderInvoiceTaxDetails]
        """
        return self._tax_details

    @tax_details.setter
    def tax_details(self, tax_details):
        """Sets the tax_details of this MerchantPurchaseOrderInvoiceLine.


        :param tax_details: The tax_details of this MerchantPurchaseOrderInvoiceLine.  # noqa: E501
        :type: list[PurchaseOrderInvoiceTaxDetails]
        """

        self._tax_details = tax_details

    @property
    def charge_details(self):
        """Gets the charge_details of this MerchantPurchaseOrderInvoiceLine.  # noqa: E501


        :return: The charge_details of this MerchantPurchaseOrderInvoiceLine.  # noqa: E501
        :rtype: list[PurchaseOrderInvoiceChargeDetails]
        """
        return self._charge_details

    @charge_details.setter
    def charge_details(self, charge_details):
        """Sets the charge_details of this MerchantPurchaseOrderInvoiceLine.


        :param charge_details: The charge_details of this MerchantPurchaseOrderInvoiceLine.  # noqa: E501
        :type: list[PurchaseOrderInvoiceChargeDetails]
        """

        self._charge_details = charge_details

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MerchantPurchaseOrderInvoiceLine, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MerchantPurchaseOrderInvoiceLine):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
