# coding: utf-8

"""
    ChannelEngine Merchant API

    ChannelEngine API for merchants  # noqa: E501

    OpenAPI spec version: 2.17.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class MerchantAcknowledgePurchaseOrderLine(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'order_line_identifier': 'str',
        'acknowledgement_code': 'PurchaseOrderAcknowledgementCode',
        'acknowledged_quantity': 'int',
        'rejection_reason': 'PurchaseOrderRejectionReason',
        'scheduled_ship_date': 'datetime',
        'scheduled_delivery_date': 'datetime'
    }

    attribute_map = {
        'order_line_identifier': 'OrderLineIdentifier',
        'acknowledgement_code': 'AcknowledgementCode',
        'acknowledged_quantity': 'AcknowledgedQuantity',
        'rejection_reason': 'RejectionReason',
        'scheduled_ship_date': 'ScheduledShipDate',
        'scheduled_delivery_date': 'ScheduledDeliveryDate'
    }

    def __init__(self, order_line_identifier=None, acknowledgement_code=None, acknowledged_quantity=None, rejection_reason=None, scheduled_ship_date=None, scheduled_delivery_date=None):  # noqa: E501
        """MerchantAcknowledgePurchaseOrderLine - a model defined in Swagger"""  # noqa: E501
        self._order_line_identifier = None
        self._acknowledgement_code = None
        self._acknowledged_quantity = None
        self._rejection_reason = None
        self._scheduled_ship_date = None
        self._scheduled_delivery_date = None
        self.discriminator = None
        if order_line_identifier is not None:
            self.order_line_identifier = order_line_identifier
        if acknowledgement_code is not None:
            self.acknowledgement_code = acknowledgement_code
        if acknowledged_quantity is not None:
            self.acknowledged_quantity = acknowledged_quantity
        if rejection_reason is not None:
            self.rejection_reason = rejection_reason
        if scheduled_ship_date is not None:
            self.scheduled_ship_date = scheduled_ship_date
        if scheduled_delivery_date is not None:
            self.scheduled_delivery_date = scheduled_delivery_date

    @property
    def order_line_identifier(self):
        """Gets the order_line_identifier of this MerchantAcknowledgePurchaseOrderLine.  # noqa: E501


        :return: The order_line_identifier of this MerchantAcknowledgePurchaseOrderLine.  # noqa: E501
        :rtype: str
        """
        return self._order_line_identifier

    @order_line_identifier.setter
    def order_line_identifier(self, order_line_identifier):
        """Sets the order_line_identifier of this MerchantAcknowledgePurchaseOrderLine.


        :param order_line_identifier: The order_line_identifier of this MerchantAcknowledgePurchaseOrderLine.  # noqa: E501
        :type: str
        """

        self._order_line_identifier = order_line_identifier

    @property
    def acknowledgement_code(self):
        """Gets the acknowledgement_code of this MerchantAcknowledgePurchaseOrderLine.  # noqa: E501


        :return: The acknowledgement_code of this MerchantAcknowledgePurchaseOrderLine.  # noqa: E501
        :rtype: PurchaseOrderAcknowledgementCode
        """
        return self._acknowledgement_code

    @acknowledgement_code.setter
    def acknowledgement_code(self, acknowledgement_code):
        """Sets the acknowledgement_code of this MerchantAcknowledgePurchaseOrderLine.


        :param acknowledgement_code: The acknowledgement_code of this MerchantAcknowledgePurchaseOrderLine.  # noqa: E501
        :type: PurchaseOrderAcknowledgementCode
        """

        self._acknowledgement_code = acknowledgement_code

    @property
    def acknowledged_quantity(self):
        """Gets the acknowledged_quantity of this MerchantAcknowledgePurchaseOrderLine.  # noqa: E501


        :return: The acknowledged_quantity of this MerchantAcknowledgePurchaseOrderLine.  # noqa: E501
        :rtype: int
        """
        return self._acknowledged_quantity

    @acknowledged_quantity.setter
    def acknowledged_quantity(self, acknowledged_quantity):
        """Sets the acknowledged_quantity of this MerchantAcknowledgePurchaseOrderLine.


        :param acknowledged_quantity: The acknowledged_quantity of this MerchantAcknowledgePurchaseOrderLine.  # noqa: E501
        :type: int
        """

        self._acknowledged_quantity = acknowledged_quantity

    @property
    def rejection_reason(self):
        """Gets the rejection_reason of this MerchantAcknowledgePurchaseOrderLine.  # noqa: E501


        :return: The rejection_reason of this MerchantAcknowledgePurchaseOrderLine.  # noqa: E501
        :rtype: PurchaseOrderRejectionReason
        """
        return self._rejection_reason

    @rejection_reason.setter
    def rejection_reason(self, rejection_reason):
        """Sets the rejection_reason of this MerchantAcknowledgePurchaseOrderLine.


        :param rejection_reason: The rejection_reason of this MerchantAcknowledgePurchaseOrderLine.  # noqa: E501
        :type: PurchaseOrderRejectionReason
        """

        self._rejection_reason = rejection_reason

    @property
    def scheduled_ship_date(self):
        """Gets the scheduled_ship_date of this MerchantAcknowledgePurchaseOrderLine.  # noqa: E501


        :return: The scheduled_ship_date of this MerchantAcknowledgePurchaseOrderLine.  # noqa: E501
        :rtype: datetime
        """
        return self._scheduled_ship_date

    @scheduled_ship_date.setter
    def scheduled_ship_date(self, scheduled_ship_date):
        """Sets the scheduled_ship_date of this MerchantAcknowledgePurchaseOrderLine.


        :param scheduled_ship_date: The scheduled_ship_date of this MerchantAcknowledgePurchaseOrderLine.  # noqa: E501
        :type: datetime
        """

        self._scheduled_ship_date = scheduled_ship_date

    @property
    def scheduled_delivery_date(self):
        """Gets the scheduled_delivery_date of this MerchantAcknowledgePurchaseOrderLine.  # noqa: E501


        :return: The scheduled_delivery_date of this MerchantAcknowledgePurchaseOrderLine.  # noqa: E501
        :rtype: datetime
        """
        return self._scheduled_delivery_date

    @scheduled_delivery_date.setter
    def scheduled_delivery_date(self, scheduled_delivery_date):
        """Sets the scheduled_delivery_date of this MerchantAcknowledgePurchaseOrderLine.


        :param scheduled_delivery_date: The scheduled_delivery_date of this MerchantAcknowledgePurchaseOrderLine.  # noqa: E501
        :type: datetime
        """

        self._scheduled_delivery_date = scheduled_delivery_date

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MerchantAcknowledgePurchaseOrderLine, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MerchantAcknowledgePurchaseOrderLine):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
