# coding: utf-8

"""
    ChannelEngine Merchant API

    ChannelEngine API for merchants  # noqa: E501

    OpenAPI spec version: 2.17.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class MerchantCreateRefund(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'order_identifier': 'str',
        'merchant_refund_no': 'str',
        'reason': 'RefundReason',
        'merchant_comment': 'str',
        'additional_amount_incl_tax': 'float',
        'shipping_amount_incl_tax': 'float',
        'refund_date': 'datetime',
        'extra_data': 'dict(str, str)',
        'lines': 'list[MerchantCreateRefundLine]'
    }

    attribute_map = {
        'order_identifier': 'OrderIdentifier',
        'merchant_refund_no': 'MerchantRefundNo',
        'reason': 'Reason',
        'merchant_comment': 'MerchantComment',
        'additional_amount_incl_tax': 'AdditionalAmountInclTax',
        'shipping_amount_incl_tax': 'ShippingAmountInclTax',
        'refund_date': 'RefundDate',
        'extra_data': 'ExtraData',
        'lines': 'Lines'
    }

    def __init__(self, order_identifier=None, merchant_refund_no=None, reason=None, merchant_comment=None, additional_amount_incl_tax=None, shipping_amount_incl_tax=None, refund_date=None, extra_data=None, lines=None):  # noqa: E501
        """MerchantCreateRefund - a model defined in Swagger"""  # noqa: E501
        self._order_identifier = None
        self._merchant_refund_no = None
        self._reason = None
        self._merchant_comment = None
        self._additional_amount_incl_tax = None
        self._shipping_amount_incl_tax = None
        self._refund_date = None
        self._extra_data = None
        self._lines = None
        self.discriminator = None
        if order_identifier is not None:
            self.order_identifier = order_identifier
        if merchant_refund_no is not None:
            self.merchant_refund_no = merchant_refund_no
        if reason is not None:
            self.reason = reason
        if merchant_comment is not None:
            self.merchant_comment = merchant_comment
        if additional_amount_incl_tax is not None:
            self.additional_amount_incl_tax = additional_amount_incl_tax
        if shipping_amount_incl_tax is not None:
            self.shipping_amount_incl_tax = shipping_amount_incl_tax
        if refund_date is not None:
            self.refund_date = refund_date
        if extra_data is not None:
            self.extra_data = extra_data
        if lines is not None:
            self.lines = lines

    @property
    def order_identifier(self):
        """Gets the order_identifier of this MerchantCreateRefund.  # noqa: E501


        :return: The order_identifier of this MerchantCreateRefund.  # noqa: E501
        :rtype: str
        """
        return self._order_identifier

    @order_identifier.setter
    def order_identifier(self, order_identifier):
        """Sets the order_identifier of this MerchantCreateRefund.


        :param order_identifier: The order_identifier of this MerchantCreateRefund.  # noqa: E501
        :type: str
        """

        self._order_identifier = order_identifier

    @property
    def merchant_refund_no(self):
        """Gets the merchant_refund_no of this MerchantCreateRefund.  # noqa: E501


        :return: The merchant_refund_no of this MerchantCreateRefund.  # noqa: E501
        :rtype: str
        """
        return self._merchant_refund_no

    @merchant_refund_no.setter
    def merchant_refund_no(self, merchant_refund_no):
        """Sets the merchant_refund_no of this MerchantCreateRefund.


        :param merchant_refund_no: The merchant_refund_no of this MerchantCreateRefund.  # noqa: E501
        :type: str
        """

        self._merchant_refund_no = merchant_refund_no

    @property
    def reason(self):
        """Gets the reason of this MerchantCreateRefund.  # noqa: E501


        :return: The reason of this MerchantCreateRefund.  # noqa: E501
        :rtype: RefundReason
        """
        return self._reason

    @reason.setter
    def reason(self, reason):
        """Sets the reason of this MerchantCreateRefund.


        :param reason: The reason of this MerchantCreateRefund.  # noqa: E501
        :type: RefundReason
        """

        self._reason = reason

    @property
    def merchant_comment(self):
        """Gets the merchant_comment of this MerchantCreateRefund.  # noqa: E501


        :return: The merchant_comment of this MerchantCreateRefund.  # noqa: E501
        :rtype: str
        """
        return self._merchant_comment

    @merchant_comment.setter
    def merchant_comment(self, merchant_comment):
        """Sets the merchant_comment of this MerchantCreateRefund.


        :param merchant_comment: The merchant_comment of this MerchantCreateRefund.  # noqa: E501
        :type: str
        """

        self._merchant_comment = merchant_comment

    @property
    def additional_amount_incl_tax(self):
        """Gets the additional_amount_incl_tax of this MerchantCreateRefund.  # noqa: E501


        :return: The additional_amount_incl_tax of this MerchantCreateRefund.  # noqa: E501
        :rtype: float
        """
        return self._additional_amount_incl_tax

    @additional_amount_incl_tax.setter
    def additional_amount_incl_tax(self, additional_amount_incl_tax):
        """Sets the additional_amount_incl_tax of this MerchantCreateRefund.


        :param additional_amount_incl_tax: The additional_amount_incl_tax of this MerchantCreateRefund.  # noqa: E501
        :type: float
        """

        self._additional_amount_incl_tax = additional_amount_incl_tax

    @property
    def shipping_amount_incl_tax(self):
        """Gets the shipping_amount_incl_tax of this MerchantCreateRefund.  # noqa: E501


        :return: The shipping_amount_incl_tax of this MerchantCreateRefund.  # noqa: E501
        :rtype: float
        """
        return self._shipping_amount_incl_tax

    @shipping_amount_incl_tax.setter
    def shipping_amount_incl_tax(self, shipping_amount_incl_tax):
        """Sets the shipping_amount_incl_tax of this MerchantCreateRefund.


        :param shipping_amount_incl_tax: The shipping_amount_incl_tax of this MerchantCreateRefund.  # noqa: E501
        :type: float
        """

        self._shipping_amount_incl_tax = shipping_amount_incl_tax

    @property
    def refund_date(self):
        """Gets the refund_date of this MerchantCreateRefund.  # noqa: E501


        :return: The refund_date of this MerchantCreateRefund.  # noqa: E501
        :rtype: datetime
        """
        return self._refund_date

    @refund_date.setter
    def refund_date(self, refund_date):
        """Sets the refund_date of this MerchantCreateRefund.


        :param refund_date: The refund_date of this MerchantCreateRefund.  # noqa: E501
        :type: datetime
        """

        self._refund_date = refund_date

    @property
    def extra_data(self):
        """Gets the extra_data of this MerchantCreateRefund.  # noqa: E501


        :return: The extra_data of this MerchantCreateRefund.  # noqa: E501
        :rtype: dict(str, str)
        """
        return self._extra_data

    @extra_data.setter
    def extra_data(self, extra_data):
        """Sets the extra_data of this MerchantCreateRefund.


        :param extra_data: The extra_data of this MerchantCreateRefund.  # noqa: E501
        :type: dict(str, str)
        """

        self._extra_data = extra_data

    @property
    def lines(self):
        """Gets the lines of this MerchantCreateRefund.  # noqa: E501


        :return: The lines of this MerchantCreateRefund.  # noqa: E501
        :rtype: list[MerchantCreateRefundLine]
        """
        return self._lines

    @lines.setter
    def lines(self, lines):
        """Sets the lines of this MerchantCreateRefund.


        :param lines: The lines of this MerchantCreateRefund.  # noqa: E501
        :type: list[MerchantCreateRefundLine]
        """

        self._lines = lines

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MerchantCreateRefund, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MerchantCreateRefund):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
