# coding: utf-8

"""
    ChannelEngine Merchant API

    ChannelEngine API for merchants  # noqa: E501

    OpenAPI spec version: 2.17.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ProductAttributeGroupRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'group_name': 'str',
        'product_extra_data_keys': 'list[str]'
    }

    attribute_map = {
        'group_name': 'GroupName',
        'product_extra_data_keys': 'ProductExtraDataKeys'
    }

    def __init__(self, group_name=None, product_extra_data_keys=None):  # noqa: E501
        """ProductAttributeGroupRequest - a model defined in Swagger"""  # noqa: E501
        self._group_name = None
        self._product_extra_data_keys = None
        self.discriminator = None
        self.group_name = group_name
        self.product_extra_data_keys = product_extra_data_keys

    @property
    def group_name(self):
        """Gets the group_name of this ProductAttributeGroupRequest.  # noqa: E501


        :return: The group_name of this ProductAttributeGroupRequest.  # noqa: E501
        :rtype: str
        """
        return self._group_name

    @group_name.setter
    def group_name(self, group_name):
        """Sets the group_name of this ProductAttributeGroupRequest.


        :param group_name: The group_name of this ProductAttributeGroupRequest.  # noqa: E501
        :type: str
        """
        if group_name is None:
            raise ValueError("Invalid value for `group_name`, must not be `None`")  # noqa: E501

        self._group_name = group_name

    @property
    def product_extra_data_keys(self):
        """Gets the product_extra_data_keys of this ProductAttributeGroupRequest.  # noqa: E501


        :return: The product_extra_data_keys of this ProductAttributeGroupRequest.  # noqa: E501
        :rtype: list[str]
        """
        return self._product_extra_data_keys

    @product_extra_data_keys.setter
    def product_extra_data_keys(self, product_extra_data_keys):
        """Sets the product_extra_data_keys of this ProductAttributeGroupRequest.


        :param product_extra_data_keys: The product_extra_data_keys of this ProductAttributeGroupRequest.  # noqa: E501
        :type: list[str]
        """
        if product_extra_data_keys is None:
            raise ValueError("Invalid value for `product_extra_data_keys`, must not be `None`")  # noqa: E501

        self._product_extra_data_keys = product_extra_data_keys

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ProductAttributeGroupRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ProductAttributeGroupRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
