# coding: utf-8

"""
    ChannelEngine Merchant API

    ChannelEngine API for merchants  # noqa: E501

    OpenAPI spec version: 2.17.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class RemoveProductExtraDataRequests(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'product_extra_data_keys': 'list[str]'
    }

    attribute_map = {
        'product_extra_data_keys': 'ProductExtraDataKeys'
    }

    def __init__(self, product_extra_data_keys=None):  # noqa: E501
        """RemoveProductExtraDataRequests - a model defined in Swagger"""  # noqa: E501
        self._product_extra_data_keys = None
        self.discriminator = None
        if product_extra_data_keys is not None:
            self.product_extra_data_keys = product_extra_data_keys

    @property
    def product_extra_data_keys(self):
        """Gets the product_extra_data_keys of this RemoveProductExtraDataRequests.  # noqa: E501


        :return: The product_extra_data_keys of this RemoveProductExtraDataRequests.  # noqa: E501
        :rtype: list[str]
        """
        return self._product_extra_data_keys

    @product_extra_data_keys.setter
    def product_extra_data_keys(self, product_extra_data_keys):
        """Sets the product_extra_data_keys of this RemoveProductExtraDataRequests.


        :param product_extra_data_keys: The product_extra_data_keys of this RemoveProductExtraDataRequests.  # noqa: E501
        :type: list[str]
        """

        self._product_extra_data_keys = product_extra_data_keys

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RemoveProductExtraDataRequests, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RemoveProductExtraDataRequests):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
